import re
import os
import sys

print(pathvar)
with open("E:\\Python\\data.txt") as d:

	for i in d:
		print(i)



# file = open("E:\\Python\\file.txt")

# content = file.read()
# print (content)

# linewise = file.readline(100)
# print (linewise)
# for line in file.readline():
	# print (line)
	# matchObj = re.match(r'(.)-(.)', line, re.M|re.I)
	# if matchObj:
		# print ("matchObj.group() : ", matchObj.group())
		# print ("matchObj.group(1) : ", matchObj.group(1))
		# print ("matchObj.group(2) : ", matchObj.group(2))
	# else:
		# print ("No match!!")

# file.close()
# with open("E:\\Python\\file.txt") as f:
# 	for line in f:
# 		# print("this is my lines " + line)
# 		matchObj = re.search(r'(.*)-(.*)', line, re.M|re.I)
# 		if matchObj:
# 			print ("matchObj.group() : ", matchObj.group() + " " + line)
# 			print ("matchObj.group(1) : ", matchObj.group(1) + " " + line)
# 			print ("matchObj.group(2) : ", matchObj.group(2)  + " " + line)
# 		else:
# 			print ("No match!! in " + line)
#
